In [3]:
import os
import pandas as pd

In [6]:
feb_df = pd.read_csv('Resources/feb_2019.csv')
feb_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,320,01:47.4,07:07.6,3160.0,Central Park West & W 76 St,40.778968,-73.973747,3283.0,W 89 St & Columbus Ave,40.788221,-73.970416,15839,Subscriber,1971,1
1,316,04:43.7,10:00.6,519.0,Pershing Square North,40.751873,-73.977706,518.0,E 39 St & 2 Ave,40.747804,-73.973442,32723,Subscriber,1964,1
2,591,06:04.0,15:55.4,3171.0,Amsterdam Ave & W 82 St,40.785247,-73.976673,3154.0,E 77 St & 3 Ave,40.773142,-73.958562,27451,Subscriber,1987,1
3,2719,07:03.5,52:22.6,504.0,1 Ave & E 16 St,40.732219,-73.981656,3709.0,W 15 St & 6 Ave,40.738046,-73.996430,21579,Subscriber,1990,1
4,303,07:35.9,12:39.5,229.0,Great Jones St,40.727434,-73.993790,503.0,E 20 St & Park Ave,40.738274,-73.987520,35379,Subscriber,1979,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
967282,291,33:26.4,38:17.9,3354.0,3 St & Prospect Park West,40.668132,-73.973638,3423.0,West Drive & Prospect Park West,40.661063,-73.979453,19780,Subscriber,1978,2
967283,437,57:45.3,05:02.5,3354.0,3 St & Prospect Park West,40.668132,-73.973638,3313.0,6 Ave & 12 St,40.666318,-73.985462,34365,Subscriber,1976,2
967284,173,11:41.2,14:34.3,3354.0,3 St & Prospect Park West,40.668132,-73.973638,3418.0,Plaza St West & Flatbush Ave,40.675021,-73.971115,25889,Subscriber,1977,1
967285,244,54:51.1,58:55.3,3354.0,3 St & Prospect Park West,40.668132,-73.973638,3346.0,Berkeley Pl & 7 Ave,40.675147,-73.975232,34649,Subscriber,1994,1
967286,387,38:42.2,45:09.5,3354.0,3 St & Prospect Park West,40.668132,-73.973638,3549.0,Grand Ave & Bergen St,40.678045,-73.962408,17299,Subscriber,1979,1

In [8]:
march_df = pd.read_csv('Resources/march_2019.csv')
march_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,219,00:06.3,03:46.1,3494.0,E 115 St & Lexington Ave,40.797911,-73.942300,3501.0,E 118 St & Madison Ave,40.801487,-73.944251,33450,Subscriber,1989,1
1,143,00:28.0,02:51.7,438.0,St Marks Pl & 1 Ave,40.727791,-73.985649,236.0,St Marks Pl & 2 Ave,40.728419,-73.987140,25626,Subscriber,1990,1
2,296,01:14.0,06:10.7,3571.0,Bedford Ave & Bergen St,40.676368,-73.952918,3549.0,Grand Ave & Bergen St,40.678045,-73.962408,35568,Subscriber,1987,1
3,478,01:14.2,09:12.8,167.0,E 39 St & 3 Ave,40.748901,-73.976049,477.0,W 41 St & 8 Ave,40.756405,-73.990026,25045,Subscriber,1964,2
4,225,01:49.3,05:34.5,3458.0,W 55 St & 6 Ave,40.763094,-73.978350,3443.0,W 52 St & 6 Ave,40.761330,-73.979820,34006,Subscriber,1979,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
943739,979,59:43.4,16:02.8,2002.0,Wythe Ave & Metropolitan Ave,40.716887,-73.963198,3656.0,E 2 St & Avenue A,40.723077,-73.985836,33630,Subscriber,1992,1
943740,779,59:48.2,12:47.5,229.0,Great Jones St,40.727434,-73.993790,519.0,Pershing Square North,40.751873,-73.977706,30765,Subscriber,1995,1
943741,699,59:48.6,11:28.6,494.0,W 26 St & 8 Ave,40.747348,-73.997236,487.0,E 20 St & FDR Drive,40.733143,-73.975739,19721,Subscriber,1996,1
943742,284,59:59.3,04:43.7,3660.0,W 16 St & 8 Ave,40.741022,-74.001385,3255.0,8 Ave & W 31 St,40.750585,-73.994685,27804,Subscriber,1985,1
943743,279,59:55.0,04:34.9,362.0,Broadway & W 37 St,40.751726,-73.987535,490.0,8 Ave & W 33 St,40.751551,-73.993934,21507,Subscriber,1969,1

In [11]:
may_df = pd.read_csv('Resources/may_2019.csv')
may_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,88,00:14.7,01:42.9,2006,Central Park S & 6 Ave,40.765909,-73.976342,2006,Central Park S & 6 Ave,40.765909,-73.976342,36515,Subscriber,1982,1
1,443,00:20.8,07:44.3,254,W 11 St & 6 Ave,40.735324,-73.998004,540,Lexington Ave & E 29 St,40.743116,-73.982154,17406,Subscriber,1983,1
2,662,00:31.0,11:33.3,3244,University Pl & E 8 St,40.731437,-73.994903,3244,University Pl & E 8 St,40.731437,-73.994903,20775,Subscriber,1988,1
3,86,00:30.9,01:57.0,526,E 33 St & 5 Ave,40.747659,-73.984907,474,5 Ave & E 29 St,40.745168,-73.986831,36270,Subscriber,1982,1
4,136,00:32.6,02:49.4,461,E 20 St & 2 Ave,40.735877,-73.982050,504,1 Ave & E 16 St,40.732219,-73.981656,36051,Subscriber,1986,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,3433,22:01.9,19:15.5,3108,Nassau Ave & Russell St,40.725570,-73.944340,217,Old Fulton St,40.702772,-73.993836,17785,Customer,1969,0
1048571,328,22:02.2,27:31.0,3263,Cooper Square & Astor Pl,40.729515,-73.990753,368,Carmine St & 6 Ave,40.730386,-74.002150,29321,Subscriber,1982,1
1048572,465,22:01.7,29:47.2,3674,Jay St & York St,40.701403,-73.986727,3648,Flushing Ave & Vanderbilt Ave,40.697950,-73.970776,16896,Subscriber,1980,1
1048573,919,22:03.5,37:23.0,297,E 15 St & 3 Ave,40.734232,-73.986923,195,Liberty St & Broadway,40.709056,-74.010434,32438,Subscriber,1970,1
1048574,402,22:02.8,28:45.3,3107,Bedford Ave & Nassau Ave,40.723117,-73.952123,3085,Roebling St & N 4 St,40.714690,-73.957390,30855,Subscriber,1982,1

In [13]:
april_df = pd.read_csv('Resources/april_2019.csv')
april_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,1463,00:16.1,24:39.4,319.0,Fulton St & Broadway,40.711066,-74.009447,347.0,Greenwich St & W Houston St,40.728846,-74.008591,35618,Subscriber,1989,1
1,285,00:32.4,05:18.2,439.0,E 4 St & 2 Ave,40.726281,-73.989780,150.0,E 2 St & Avenue C,40.720874,-73.980858,31113,Subscriber,1980,1
2,686,00:47.8,12:14.3,526.0,E 33 St & 5 Ave,40.747659,-73.984907,3474.0,6 Ave & Spring St,40.725256,-74.004121,19617,Subscriber,1987,1
3,442,01:01.2,08:23.8,3474.0,6 Ave & Spring St,40.725256,-74.004121,355.0,Bayard St & Baxter St,40.716021,-73.999744,27086,Subscriber,1987,2
4,2913,01:09.3,49:42.4,379.0,W 31 St & 7 Ave,40.749156,-73.991600,212.0,W 16 St & The High Line,40.743349,-74.006818,34791,Subscriber,1991,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,272,28:28.3,33:01.0,349.0,Rivington St & Ridge St,40.718502,-73.983299,342.0,Columbia St & Rivington St,40.717400,-73.980166,14914,Subscriber,1974,2
1048571,615,28:26.6,38:42.3,466.0,W 25 St & 6 Ave,40.743954,-73.991449,3236.0,W 42 St & Dyer Ave,40.758985,-73.993800,37461,Subscriber,1994,1
1048572,1084,28:23.3,46:27.3,3259.0,9 Ave & W 28 St,40.749370,-73.999234,509.0,9 Ave & W 22 St,40.745497,-74.001971,35349,Subscriber,1993,1
1048573,511,28:23.6,36:55.2,492.0,W 33 St & 7 Ave,40.750200,-73.990931,3699.0,W 50 St & 9 Ave,40.763605,-73.989180,37628,Subscriber,1990,1
1048574,173,28:29.5,31:23.3,402.0,Broadway & E 22 St,40.740343,-73.989551,3707.0,Lexington Ave & E 26 St,40.741459,-73.983293,14577,Subscriber,1982,1

In [14]:
combined_data = pd.concat((feb_df, march_df, april_df, may_df), axis=0)
combined_data

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,320,01:47.4,07:07.6,3160.0,Central Park West & W 76 St,40.778968,-73.973747,3283.0,W 89 St & Columbus Ave,40.788221,-73.970416,15839,Subscriber,1971,1
1,316,04:43.7,10:00.6,519.0,Pershing Square North,40.751873,-73.977706,518.0,E 39 St & 2 Ave,40.747804,-73.973442,32723,Subscriber,1964,1
2,591,06:04.0,15:55.4,3171.0,Amsterdam Ave & W 82 St,40.785247,-73.976673,3154.0,E 77 St & 3 Ave,40.773142,-73.958562,27451,Subscriber,1987,1
3,2719,07:03.5,52:22.6,504.0,1 Ave & E 16 St,40.732219,-73.981656,3709.0,W 15 St & 6 Ave,40.738046,-73.996430,21579,Subscriber,1990,1
4,303,07:35.9,12:39.5,229.0,Great Jones St,40.727434,-73.993790,503.0,E 20 St & Park Ave,40.738274,-73.987520,35379,Subscriber,1979,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,3433,22:01.9,19:15.5,3108.0,Nassau Ave & Russell St,40.725570,-73.944340,217.0,Old Fulton St,40.702772,-73.993836,17785,Customer,1969,0
1048571,328,22:02.2,27:31.0,3263.0,Cooper Square & Astor Pl,40.729515,-73.990753,368.0,Carmine St & 6 Ave,40.730386,-74.002150,29321,Subscriber,1982,1
1048572,465,22:01.7,29:47.2,3674.0,Jay St & York St,40.701403,-73.986727,3648.0,Flushing Ave & Vanderbilt Ave,40.697950,-73.970776,16896,Subscriber,1980,1
1048573,919,22:03.5,37:23.0,297.0,E 15 St & 3 Ave,40.734232,-73.986923,195.0,Liberty St & Broadway,40.709056,-74.010434,32438,Subscriber,1970,1
1048574,402,22:02.8,28:45.3,3107.0,Bedford Ave & Nassau Ave,40.723117,-73.952123,3085.0,Roebling St & N 4 St,40.714690,-73.957390,30855,Subscriber,1982,1

In [20]:
combined_data.to_csv(r'C:\Users\mlinc\Desktop\combined_data_citibikes.csv', index=False)